# Generated by Django 5.2.1 on 2025-07-26 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppTicaret", "0009_order_orderitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-create_date"], "verbose_name_plural": "Yorumlar"},
        ),
        migrations.RemoveField(
            model_name="brand",
            name="brand_en",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="brand_tr",
        ),
        migrations.RemoveField(
            model_name="caseshape",
            name="case_shape_en",
        ),
        migrations.RemoveField(
            model_name="caseshape",
            name="case_shape_tr",
        ),
        migrations.RemoveField(
            model_name="color",
            name="color_en",
        ),
        migrations.RemoveField(
            model_name="color",
            name="color_tr",
        ),
        migrations.RemoveField(
            model_name="gender",
            name="gender_en",
        ),
        migrations.RemoveField(
            model_name="gender",
            name="gender_tr",
        ),
        migrations.RemoveField(
            model_name="glassfeature",
            name="glass_feature_en",
        ),
        migrations.RemoveField(
            model_name="glassfeature",
            name="glass_feature_tr",
        ),
        migrations.RemoveField(
            model_name="mechanism",
            name="mechanism_en",
        ),
        migrations.RemoveField(
            model_name="mechanism",
            name="mechanism_tr",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_tr",
        ),
        migrations.RemoveField(
            model_name="product",
            name="model_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="model_tr",
        ),
        migrations.RemoveField(
            model_name="straptype",
            name="strap_type_en",
        ),
        migrations.RemoveField(
            model_name="straptype",
            name="strap_type_tr",
        ),
        migrations.RemoveField(
            model_name="style",
            name="style_en",
        ),
        migrations.RemoveField(
            model_name="style",
            name="style_tr",
        ),
        migrations.AddField(
            model_name="comment",
            name="is_verified_purchase",
            field=models.BooleanField(
                default=False, verbose_name="Doğrulanmış Satın Alma"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Yıldız"),
                    (2, "2 Yıldız"),
                    (3, "3 Yıldız"),
                    (4, "4 Yıldız"),
                    (5, "5 Yıldız"),
                ],
                default=5,
                verbose_name="Puan",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(max_length=500, verbose_name="Yorum"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Yorum Tarihi"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="AppTicaret.product",
                verbose_name="Ürün",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Kargo Takip Numarası",
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Adres Başlığı"),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[("home", "Ev"), ("work", "İş"), ("other", "Diğer")],
                        default="home",
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=50, verbose_name="Soyad")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("city", models.CharField(max_length=50, verbose_name="İl")),
                ("district", models.CharField(max_length=50, verbose_name="İlçe")),
                (
                    "neighborhood",
                    models.CharField(max_length=50, verbose_name="Mahalle"),
                ),
                ("address", models.TextField(verbose_name="Açık Adres")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Varsayılan Adres"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Adresler",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="AppTicaret.address",
                verbose_name="Teslimat Adresi",
            ),
        ),
        migrations.DeleteModel(
            name="Adress",
        ),
    ]
