# Generated by Django 5.2.1 on 2025-07-26 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppTicaret", "0011_alter_product_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Product Images", verbose_name="Ürün Görseli"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt Metin"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Ana Görsel"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="AppTicaret.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ürün Görselleri",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
