# Generated by Django 5.2.1 on 2025-07-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppTicaret", "0012_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="Stok Miktarı"),
        ),
    ]
