# Generated by Django 5.2.1 on 2025-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTicaret', '0013_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Yıldız'), (2, '2 Yıldız'), (3, '3 Yıldız'), (4, '4 Yıldız'), (5, '5 Yıldız')], default=5, verbose_name='Puan'),
        ),
    ] 