# Generated by Django 5.2.1 on 2025-07-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTicaret', '0014_add_rating_to_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='E-posta Doğrulandı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verification_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Telefon Doğrulandı'),
        ),
    ]
