# Generated by Django 5.2.1 on 2025-07-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTicaret', '0015_profile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_verification_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_verification_expires',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_verified',
        ),
    ]
